### ISSUE TITLE
CORS issues with fonts

### ISSUE THREAD

**Issue by jdarrohn** [hellosign/hellosign-embedded#143] opened 2020-02-13 23:09 UTC
**Note:** I already saw this issue here that has been closed out:
https://github.com/hellosign/hellosign-embedded/issues/57

We are receiving similar errors now, where `app.hellosign.com` is having difficult hitting `cdn.hellosign.com`. Other times, we are seeing issues with CORS and Adobe TypeKit.

![Screen Shot 2020-02-13 at 10 05 21 AM](https://user-images.githubusercontent.com/7231602/74486838-2d873100-4e7b-11ea-99df-4bc06fd94fd9.png)

These issues seem to break the embedded code and users are "trapped" inside the document with no navigation.

**Comment by nathanbuchar** [comment] 2020-02-14 18:10
HelloSign Embedded is just a library which wraps `app.hellosign.com`, so I bet the issue is actually coming from our signer app. I'll forward to that team to take a look into this issue!

**Comment by latoyazamill** [comment] 2020-02-14 18:18
Hi @jdarrohn We will close this issue and continue to discuss in the support ticket that has been opened. Thanks!

**Closed by latoyazamill** 2020-02-14 18:18 UTC
