### ISSUE TITLE
Unable to close embedded iframe

### ISSUE THREAD

**Issue by jamesloewen** [hellosign/hellosign-embedded#112] opened 2019-04-03 18:24 UTC
Experienced in version 2.3.0

I am opening a claim url, configuration is:
```
_hsInstance = new HelloSign({
   clientId: 'my-client-id',
   testMode: false,
});
```
And opening with
```
_hsInstance.open(claimUrl);
```

In this environment, the close button in the top right is visible but clicking on it does nothing

**Comment by jamesloewen** [comment] 2019-04-03 22:42
In general it seems like the events aren't being received correctly because https://github.com/hellosign/hellosign-embedded/blob/master/src/embedded.js#L1042 is attached to the window rather than the iFrame

Note: Tested by calling https://github.com/hellosign/hellosign-embedded/blob/master/src/embedded.js#L516 with the window instead of iFrame and `_onMessage` is now being called.

**Comment by nathanbuchar** [comment] 2019-04-08 17:45
Noted, I'll take a look. Thanks for the report

**Comment by nathanbuchar** [comment] 2019-04-08 17:47
@jamesloewen in your note, did you said:

> with *the window* instead of *iFrame* and `_onMessage` is now being called.

But did you mean to say?

> with the *iFrame* instead of the *window* and `_onMessage` is now being called.

Just want to make sure I'm understanding correctly so I can better troubleshoot the issue

**Comment by jamesloewen** [comment] 2019-04-08 17:56
I called it directly on the `window` (where the listener is attached) and got the debugger in `_onMessage` triggered.

Calling it on the `iFrame` is what is currently happening and appears to be causing the bad behavior. I did not adjust the event listener at all.

I imagine attaching the event listener onto the iFrame will resolve it without polluting top level scope

**Comment by nathanbuchar** [comment] 2019-04-08 17:58
Interesting, because when I was developing the library, I had originally added the event listener to the frame instead of the window, but it was never triggering. Adding it to the window instead fixed those issues. 

Which browser are you using? Perhaps different browsers handle this differently (I should hope not).

**Comment by jamesloewen** [comment] 2019-04-08 18:03
This was tested using Chrome 72 and I think I tested on latest Firefox as well but can't remember specifically.

Cross browser behavior was definitely something that crossed my mind as for why this would crop up. I've also never worked directly with iFrames so not sure what all the headaches are around edge cases on that

**Comment by nathanbuchar** [comment] 2019-04-08 18:19
Just mocked something up really quick:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>HelloSign Embedded v2 Test</title>
  <script src="https://cdn.hellosign.com/public/js/embedded/v2.3.0/embedded.development.js"></script>
</head>
<body>
  <form>
    <input type="text" name="client-id">
    <input type="url" name="url">
    <button type="submit">Open</button>
  </form>
  <script>
    const client = new HelloSign({
      testMode: true,
    });

    const formElem = document.forms[0];
    const clientIdElem = formElem.elements.namedItem('client-id');
    const urlElem = formElem.elements.namedItem('url');

    document.forms[0].addEventListener('submit', (evt) => {
      evt.preventDefault();

      const clientId = clientIdElem.value;
      const url = urlElem.value;

      client.open(url, {
        clientId,
      });
    });
  </script>
</body>
</html>
```

This worked fine for me (Chrome Version 73.0.3683.86)

**Comment by jamesloewen** [comment] 2019-04-08 18:30
Hmm, I'll keep looking, see if that works for me as well. Thanks for looking into this

**Comment by nathanbuchar** [comment] 2019-04-08 18:49
If you're still experiencing issues, I'd recommend reaching out to apisupport@hellosign.com. They're a dedicated team for helping with these kinds of issues. There might be some edge case with your implementation or quite possibly a bug in our app code somewhere, but they'll be able to troubleshoot the problem more effectively than I for the time being :)

**Comment by nathanbuchar** [comment] 2019-04-08 18:56
Quick q, when you click the close button, do you see `sending cancel request message` logged to the console via debug?

**Comment by nathanbuchar** [comment] 2019-04-23 17:55
@jamesloewen Just wanted to check in and see how things are going. I understand you're using a combination of both v1 and v2, and I would love to help you get v2 working 100% :)

My initial impression was that you were using HS Embedded in the browser, but from what I hear you're actually using it within a mobile app? Can you tell me about the architecture? Are you using React Native, Swift, Objective-C? Are you installing via npm? Which module bundler are you using (Webpack, rollup, etc.)?

This bug may be a result of the environment (native iOS) having not been tested and some edgecases may be showing their heads. Definitely want to get to the bottom of it :)

**Comment by jamesloewen** [comment] 2019-04-23 17:59
We are using it in browser, not sure where mobile would have come from (didn't realize that was even possible). I've been super busy the last 2 weeks and preoccupied with other tasks so I ended up rolling back to V1 for now and making the other improvements I needed on that version.

I hope to revisit this over the next few weeks, but not sure where that lands unfortunately.

We are installing from npm, bundling with webpack for browser.

**Comment by nathanbuchar** [comment] 2019-04-23 18:02
Thanks for the update. With respect to mobile, I may have my wires crossed :) Apologies! I'll check back in with the API Support team to make sure I'm referencing the correct account

**Comment by jamesloewen** [comment] 2019-05-01 20:42
Okay, finally got around to testing today.

Close button seems to be fine in the example you provided above (although the signature request wasn't fully loading, not sure if that is an equivalent test), but still having the issue on our end. I suspect some of our code is somehow conflicting with HS and not sure what that is.

Will post back if I figure out a solution or at least figure out how to reproduce it

**Comment by jamesloewen** [comment] 2019-05-01 22:01
At https://github.com/hellosign/hellosign-embedded/blob/master/src/embedded.js#L857 if you force `this._isReady` to true, you can replicate the issue I'm having in the example provided at https://github.com/hellosign/hellosign-embedded/issues/112#issuecomment-480946598

Currently running Chrome 73.0.3683.103 on Mojave

**Comment by nathanbuchar** [comment] 2019-05-02 23:03
@jamesloewen one of our in-house developers also ran into this issue using embedded templates. I'm seeing that HelloSign Embedded is sending the close request to the server, but it appears that the HelloSign app itself is not posting the close confirm message back to Embedded. I suspect the problem he is our app code, not HelloSign Embedded.

I'll dig into this some more :)

**Comment by nathanbuchar** [comment] 2019-05-08 22:22
@jamesloewen are you by chance specifying a `redirectTo` URL?

**Comment by jamesloewen** [comment] 2019-05-08 22:26
I am not

**Comment by notadamking** [comment] 2019-05-15 01:40
We are experiencing this issue as well. Any resolutions yet?

**Comment by nathanbuchar** [comment] 2019-06-06 17:30
Just wanted to give an update. I'm sorry for the delay in this, I've been pretty booked solid on other work, but one of our engineers is currently in the process of fixing this right now. 

We've identified the problem as an issue with HelloSign proper, not the HelloSign Embedded library. Something around how we validate the window message origin on the HelloSign app side. Because this is an issue in the HelloSign app, the fix will follow our usual three-week release cycle. When the fix has been deployed, I'll update this ticket :)

**Comment by ayushnawani** [comment] 2019-06-24 18:30
Hi @nathanbuchar, I am also unable to close the iframe modal. I any idea when it will be fixed? 

Thanks

**Comment by nathanbuchar** [comment] 2019-06-26 21:02
The fix is already slated into the next development sprint. No worries, a fix is coming! The root of the issue is known, it just has to go through the formal process. Unfortunately, because this is an issue with our core codebase and not this repo in particular, it may be a few weeks just because of the red tape involved with QAing and publishing code (we're SOC2 compliant), but in the meantime you should be able to manually close the modal when a user has finished an embedded flow by hooking into the `finish` event by implementing the following:

```js
client.on('finish', () => {
  client.close();
});
```

If that doesn't work let me know :)

**Comment by nathanbuchar** [comment] 2019-08-05 17:13
Hey all, we had a production release last week and all seems stable. This bug _should_ be fixed now. As it was an issue with our HelloSign internal codebase and not this library itself, at the moment there is no need to update HelloSign Embedded, it should start working automatically.

Please let me know if you continue to run into problems. I'm sorry about the delay, being a SOC 2-compliant with limited frontend resources means a lot of red tape and planning, even for trivial fixes like this one :)

**Closed** 2019-08-05 17:14 UTC
Labels: bug, moved internally

**Comment by jamesloewen** [comment] 2019-08-12 20:08
Looks like the issue was resolved for me. @nathanbuchar do you happen to know what events should be triggered from hitting the close button there?
